apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: seba-role
  namespace: kube-system
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
      - seba-policy
